description "Fitecash Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env FITECASHD_BIN="/usr/bin/fitecashd"
env FITECASHD_USER="fitecash"
env FITECASHD_GROUP="fitecash"
env FITECASHD_PIDDIR="/var/run/fitecashd"
# upstart can't handle variables constructed with other variables
env FITECASHD_PIDFILE="/var/run/fitecashd/fitecashd.pid"
env FITECASHD_CONFIGFILE="/etc/fitecash/fitecash.conf"
env FITECASHD_DATADIR="/var/lib/fitecashd"

expect fork

respawn
respawn limit 5 120
kill timeout 60

pre-start script
    # this will catch non-existent config files
    # fitecashd will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$FITECASHD_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run fitecashd."
        echo "The setting must appear in $FITECASHD_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following"
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is also recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Fitecash Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$FITECASHD_PIDDIR"
    chmod 0755 "$FITECASHD_PIDDIR"
    chown $FITECASHD_USER:$FITECASHD_GROUP "$FITECASHD_PIDDIR"
    chown $FITECASHD_USER:$FITECASHD_GROUP "$FITECASHD_CONFIGFILE"
    chmod 0660 "$FITECASHD_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$FITECASHD_PIDFILE" \
    --chuid $FITECASHD_USER:$FITECASHD_GROUP \
    --exec "$FITECASHD_BIN" \
    -- \
    -pid="$FITECASHD_PIDFILE" \
    -conf="$FITECASHD_CONFIGFILE" \
    -datadir="$FITECASHD_DATADIR" \
    -disablewallet \
    -daemon

