#!/bin/bash
#
#  fitecashd The fitecash core server.
#
#
# chkconfig: 345 80 20
# description: fitecashd
# processname: fitecashd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/fitecashd, see below
if [ -f /etc/sysconfig/fitecashd ]; then
        . /etc/sysconfig/fitecashd
fi

RETVAL=0

prog=fitecashd
# you can override the lockfile via FITECASHD_LOCKFILE in /etc/sysconfig/fitecashd
lockfile=${FITECASHD_LOCKFILE-/var/lock/subsys/fitecashd}

# fitecashd defaults to /usr/bin/fitecashd, override with FITECASHD_BIN
fitecashd=${FITECASHD_BIN-/usr/bin/fitecashd}

# fitecashd opts default to -disablewallet, override with FITECASHD_OPTS
fitecashd_opts=${FITECASHD_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $fitecashd $fitecashd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
